# Generated by Django 4.0 on 2023-08-06 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.IntegerField(db_column='Index', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Appareil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppareilType',
            fields=[
                ('id', models.IntegerField(db_column='Index', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'AppareilType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.IntegerField(db_column='Index', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Etablissement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.AutoField(db_column='Index', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='code', max_length=30, unique=True)),
                ('nom', models.CharField(blank=True, db_column='nom', max_length=30, null=True)),
                ('nomutil', models.CharField(blank=True, db_column='nom utilisation', max_length=30, null=True)),
                ('tel', models.CharField(db_column='telephone', max_length=30, unique=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Localisation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.IntegerField(db_column='Index', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Marque',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, null=True, unique=True)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Vlan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.AutoField(db_column='Index', primary_key=True, serialize=False)),
                ('addrip', models.DecimalField(db_column='Adresse Ip', decimal_places=0, max_digits=12)),
                ('aet', models.CharField(db_column='Aet', max_length=30)),
                ('port', models.IntegerField(db_column='Port')),
                ('masque', models.DecimalField(db_column='Masque', decimal_places=0, max_digits=12)),
                ('modalite', models.CharField(db_column='Modalite', max_length=2)),
                ('hostname', models.CharField(db_column='Hostname', max_length=30)),
                ('systeme', models.CharField(db_column='Systeme', max_length=30)),
                ('macadresse', models.CharField(blank=True, db_column='Macadresse', max_length=17, null=True)),
                ('dicom', models.CharField(blank=True, db_column='Dicom', max_length=3, null=True)),
                ('inventaire', models.CharField(blank=True, db_column='Inventaire', max_length=24, null=True)),
                ('remarque', models.CharField(blank=True, db_column='remarque', max_length=1024, null=True)),
                ('appareil', models.ForeignKey(blank=True, help_text=' Appareil ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Appareil', to='imagerie.appareil')),
                ('etablissement', models.ForeignKey(blank=True, help_text=' Etablissement ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Etablissement', to='imagerie.etablissement')),
                ('localisation', models.ForeignKey(blank=True, help_text=' Localisation ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Localisation', to='imagerie.localisation')),
                ('marque', models.ForeignKey(blank=True, help_text=' Marque ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Marque', to='imagerie.marque')),
                ('typeappareil', models.ForeignKey(blank=True, help_text=' AppareilType ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AppareilType', to='imagerie.appareiltype')),
                ('vlan', models.ForeignKey(blank=True, help_text=' Vlan ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Vlan', to='imagerie.vlan')),
            ],
            options={
                'db_table': 'Liste',
                'managed': True,
            },
        ),
    ]
