# Generated by Django 4.0 on 2023-10-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Appareil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Appareiltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'AppareilType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('identif', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Bdd',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Compte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.IntegerField(blank=True, null=True, unique=True)),
                ('site', models.CharField(blank=True, max_length=45, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Etablissement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('nomutil', models.CharField(blank=True, max_length=30, null=True)),
                ('tel', models.CharField(blank=True, max_length=30, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Localisation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Logiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('version', models.CharField(blank=True, max_length=30, null=True)),
                ('editeur', models.CharField(blank=True, max_length=30, null=True)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
                ('tel', models.CharField(blank=True, max_length=30, null=True)),
                ('referent', models.CharField(blank=True, max_length=30, null=True)),
                ('marche', models.CharField(blank=True, max_length=30, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('datereforme', models.DateTimeField(auto_now=True, verbose_name='date de reforme')),
            ],
            options={
                'db_table': 'Logiciel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Marque',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srvdicom', models.BooleanField(default=False)),
                ('modalite', models.CharField(blank=True, max_length=2, null=True)),
                ('addrip', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True)),
                ('mask', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True)),
                ('passerelle', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True)),
                ('aet', models.CharField(blank=True, max_length=30, null=True)),
                ('port', models.IntegerField()),
                ('hostname', models.CharField(blank=True, max_length=30, null=True)),
                ('macadresse', models.CharField(blank=True, max_length=17, null=True)),
                ('systeme', models.CharField(blank=True, max_length=30, null=True)),
                ('inventaire', models.CharField(blank=True, max_length=24, null=True)),
                ('divers', models.CharField(blank=True, max_length=1024, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('datereforme', models.DateTimeField(auto_now=True, verbose_name='date de reforme')),
                ('mod_appareilid', models.ForeignKey(blank=True, help_text=' Appareil ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Appareil', to='imagerie.appareil')),
                ('mod_appareiltypeid', models.ForeignKey(blank=True, help_text=' Appareiltype ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Appareiltype', to='imagerie.appareiltype')),
                ('mod_etablissementid', models.ForeignKey(blank=True, help_text=' Etablissement ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Etablissement', to='imagerie.etablissement')),
                ('mod_localisationid', models.ForeignKey(blank=True, help_text=' Localisation ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Localisation', to='imagerie.localisation')),
                ('mod_marqueid', models.ForeignKey(blank=True, help_text=' Marque ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Marque', to='imagerie.marque')),
            ],
            options={
                'db_table': 'Modalite',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('editeur', models.CharField(blank=True, max_length=50, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('datereforme', models.DateTimeField(auto_now=True, verbose_name='date de reforme')),
                ('logicielid', models.ForeignKey(blank=True, help_text=' Logiciel ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Logiciel', to='imagerie.logiciel')),
            ],
            options={
                'db_table': 'Projet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('prenom', models.CharField(blank=True, max_length=30, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=30, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Ras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resspartage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('identif', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Resspartage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.IntegerField(blank=True, null=True, unique=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Service',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True, unique=True)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'db_table': 'Vlan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Testlan',
            fields=[
                ('modalite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='imagerie.modalite')),
                ('pingip', models.BooleanField(default=False)),
                ('pinghost', models.BooleanField(default=False)),
                ('pingdicom', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Testlan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srvdicom', models.BooleanField(default=False)),
                ('modalite', models.CharField(blank=True, max_length=2, null=True)),
                ('hostname', models.CharField(blank=True, max_length=30, null=True)),
                ('addrip', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('editeur', models.CharField(blank=True, max_length=30, null=True)),
                ('ram', models.CharField(blank=True, max_length=10, null=True)),
                ('cores', models.IntegerField()),
                ('ddsystem', models.CharField(blank=True, max_length=10, null=True)),
                ('dddata', models.CharField(blank=True, max_length=10, null=True)),
                ('os', models.CharField(blank=True, max_length=30, null=True)),
                ('systeme', models.CharField(blank=True, max_length=30, null=True)),
                ('inventaire', models.CharField(blank=True, max_length=24, null=True)),
                ('divers', models.CharField(blank=True, max_length=1024, null=True)),
                ('datecreat', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('datemodif', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('datereforme', models.DateTimeField(auto_now=True, verbose_name='date de reforme')),
                ('bddid', models.ForeignKey(blank=True, help_text=' Base de données ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bdd', to='imagerie.bdd')),
                ('comptesid', models.ForeignKey(blank=True, help_text=' Compte ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Compte', to='imagerie.compte')),
                ('projetid', models.ForeignKey(blank=True, help_text=' Projet ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Projet', to='imagerie.projet')),
                ('rasid', models.ForeignKey(blank=True, help_text=' compte ras_xxx ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ras', to='imagerie.ras')),
                ('resspartageid', models.ForeignKey(blank=True, help_text=' Ressource partagée ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Resspartage', to='imagerie.resspartage')),
                ('ser_appareilid', models.ForeignKey(blank=True, help_text=' Appareil ', null=True, on_delete=django.db.models.deletion.PROTECT, to='imagerie.appareil')),
                ('ser_appareiltypeid', models.ForeignKey(blank=True, help_text=' Appareiltype ', null=True, on_delete=django.db.models.deletion.PROTECT, to='imagerie.appareiltype')),
                ('ser_etablissementid', models.ForeignKey(blank=True, help_text=' Etablissement ', null=True, on_delete=django.db.models.deletion.PROTECT, to='imagerie.etablissement')),
                ('ser_localisationid', models.ForeignKey(blank=True, help_text=' Localisation ', null=True, on_delete=django.db.models.deletion.PROTECT, to='imagerie.localisation')),
                ('ser_marqueid', models.ForeignKey(blank=True, help_text=' Marque ', null=True, on_delete=django.db.models.deletion.PROTECT, to='imagerie.marque')),
                ('ser_vlanid', models.ForeignKey(blank=True, help_text=' Vlan ', null=True, on_delete=django.db.models.deletion.PROTECT, to='imagerie.vlan')),
            ],
            options={
                'db_table': 'Serveur',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='projet',
            name='service',
            field=models.ForeignKey(blank=True, help_text=' Service ', null=True, on_delete=django.db.models.deletion.PROTECT, to='imagerie.service'),
        ),
        migrations.AddField(
            model_name='modalite',
            name='mod_serveurid',
            field=models.ForeignKey(blank=True, help_text=' Serveur ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Serveur', to='imagerie.serveur'),
        ),
        migrations.AddField(
            model_name='modalite',
            name='mod_vlanid',
            field=models.ForeignKey(blank=True, help_text=' Vlan ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Vlan', to='imagerie.vlan'),
        ),
        migrations.AddField(
            model_name='modalite',
            name='pacs',
            field=models.ManyToManyField(blank=True, to='imagerie.Modalite'),
        ),
        migrations.AddField(
            model_name='modalite',
            name='service',
            field=models.ForeignKey(blank=True, help_text=' Service ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Service', to='imagerie.service'),
        ),
        migrations.AddField(
            model_name='modalite',
            name='store',
            field=models.ManyToManyField(blank=True, to='imagerie.Modalite'),
        ),
        migrations.AddField(
            model_name='modalite',
            name='worklist',
            field=models.ManyToManyField(blank=True, to='imagerie.Modalite'),
        ),
    ]
