# Generated by Django 4.0 on 2023-10-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='nom',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
