# Generated by Django 4.0 on 2023-10-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0002_alter_etablissement_nom_alter_service_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serveur',
            old_name='ser_appareilid',
            new_name='appareilid',
        ),
        migrations.RenameField(
            model_name='serveur',
            old_name='ser_appareiltypeid',
            new_name='appareiltypeid',
        ),
        migrations.RenameField(
            model_name='serveur',
            old_name='ser_etablissementid',
            new_name='etablissementid',
        ),
        migrations.RenameField(
            model_name='serveur',
            old_name='ser_localisationid',
            new_name='localisationid',
        ),
        migrations.RenameField(
            model_name='serveur',
            old_name='ser_marqueid',
            new_name='marqueid',
        ),
        migrations.RenameField(
            model_name='serveur',
            old_name='ser_vlanid',
            new_name='vlanid',
        ),
    ]
