# Generated by Django 4.0 on 2023-10-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0003_rename_ser_appareilid_serveur_appareilid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
