# Generated by Django 4.0 on 2023-08-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0004_alter_liste_aet_alter_liste_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='serveur',
            field=models.BooleanField(default=False),
        ),
    ]
