# Generated by Django 4.0 on 2023-10-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0004_alter_localisation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modalite',
            old_name='mod_appareilid',
            new_name='appareilid',
        ),
        migrations.RenameField(
            model_name='modalite',
            old_name='mod_appareiltypeid',
            new_name='appareiltypeid',
        ),
        migrations.RenameField(
            model_name='modalite',
            old_name='mod_etablissementid',
            new_name='etablissementid',
        ),
        migrations.RenameField(
            model_name='modalite',
            old_name='mod_localisationid',
            new_name='localisationid',
        ),
        migrations.RenameField(
            model_name='modalite',
            old_name='mod_marqueid',
            new_name='marqueid',
        ),
        migrations.RenameField(
            model_name='modalite',
            old_name='mod_serveurid',
            new_name='serveurid',
        ),
        migrations.RenameField(
            model_name='modalite',
            old_name='mod_vlanid',
            new_name='vlanid',
        ),
    ]
