# Generated by Django 4.0 on 2023-08-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0005_liste_serveur'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='typeserveur',
            field=models.ManyToManyField(blank=True, choices=[('0', 'N/A'), ('1', 'PACS'), ('2', 'WL'), ('3', 'DACS'), ('4', 'STORE'), ('5', 'PRINT')], default=0, null=True, to='imagerie.Liste'),
        ),
    ]
