# Generated by Django 4.0 on 2023-08-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0006_liste_typeserveur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connect',
            new_name='Testlan',
        ),
        migrations.RemoveField(
            model_name='liste',
            name='typeserveur',
        ),
        migrations.AddField(
            model_name='liste',
            name='connexion',
            field=models.ManyToManyField(blank=True, to='imagerie.Liste'),
        ),
        migrations.AlterModelTable(
            name='testlan',
            table='Testlan',
        ),
    ]
