# Generated by Django 4.0 on 2023-10-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0007_rename_vlanid_machine_vlan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='password',
            field=models.CharField(blank=True, default='voir TeamPass', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='modalite',
            name='mask',
            field=models.GenericIPAddressField(blank=True, default='255.255.255.0', null=True),
        ),
        migrations.RemoveField(
            model_name='modalite',
            name='pacs',
        ),
        migrations.AddField(
            model_name='modalite',
            name='pacs',
            field=models.ForeignKey(blank=True, help_text=' Pacs ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Pacs', to='imagerie.modalite'),
        ),
        migrations.AlterField(
            model_name='modalite',
            name='passerelle',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.1', null=True),
        ),
        migrations.RemoveField(
            model_name='modalite',
            name='worklist',
        ),
        migrations.AddField(
            model_name='modalite',
            name='worklist',
            field=models.ForeignKey(blank=True, help_text=' Worklist ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Worklist', to='imagerie.modalite'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='logiciel',
            field=models.ForeignKey(blank=True, help_text=' Logiciel ', null=True, on_delete=django.db.models.deletion.PROTECT, to='imagerie.logiciel'),
        ),
        migrations.AlterField(
            model_name='resspartage',
            name='password',
            field=models.CharField(blank=True, default='voir TeamPass', max_length=30, null=True),
        ),
    ]
