# Generated by Django 4.0 on 2023-10-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0008_alter_compte_password_alter_modalite_mask_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'managed': True, 'ordering': ['addrip']},
        ),
        migrations.AlterModelOptions(
            name='modalite',
            options={'managed': True, 'ordering': ['aet']},
        ),
        migrations.AlterModelOptions(
            name='serveur',
            options={'managed': True, 'ordering': ['projet']},
        ),
        migrations.AlterField(
            model_name='serveur',
            name='cores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
