# Generated by Django 4.0 on 2023-10-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0010_remove_serveur_modalite_remove_serveur_srvdicom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compte',
            new_name='Identifiant',
        ),
        migrations.RemoveField(
            model_name='serveur',
            name='comptes',
        ),
        migrations.AddField(
            model_name='serveur',
            name='identifiant',
            field=models.ManyToManyField(help_text=' Identifiant ', to='imagerie.Identifiant'),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='type',
            field=models.CharField(blank=True, default='VM', help_text=' VM / Physique ', max_length=30, null=True),
        ),
    ]
