# Generated by Django 4.0 on 2023-10-27 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0011_rename_compte_identifiant_remove_serveur_comptes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalite',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='modalite',
            name='modedegrade',
            field=models.CharField(blank=True, choices=[('0', 'N/A'), ('1', 'PACS'), ('2', 'WL'), ('3', 'DACS'), ('4', 'STORE'), ('5', 'PRINT'), ('6', 'OTHER')], help_text=' mode dégradé à mettre en place.. ', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='modalite',
            name='modalite',
            field=models.CharField(blank=True, help_text=' CT, CR, DX, US, MR, etc... ', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='modalite',
            name='port',
            field=models.IntegerField(blank=True, help_text=' Port DICOM ', null=True),
        ),
        migrations.AlterField(
            model_name='modalite',
            name='serveur',
            field=models.ForeignKey(blank=True, help_text=' Serveur associé ? ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Serveur', to='imagerie.serveur'),
        ),
        migrations.AlterField(
            model_name='modalite',
            name='srvdicom',
            field=models.CharField(blank=True, choices=[('0', 'N/A'), ('1', 'PACS'), ('2', 'WL'), ('3', 'DACS'), ('4', 'STORE'), ('5', 'PRINT'), ('6', 'OTHER')], default='JANUARY', help_text=' type de serveur ', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='modalite',
            name='store',
            field=models.ManyToManyField(blank=True, help_text=" différents STORE où l'on peut pousser les examens", to='imagerie.Modalite'),
        ),
    ]
